// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShLKUvRcA0O6QTgH4ZL7QthTAIyFnohM',
    appId: '1:106870549521:web:0f123668e7efb9f97c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    authDomain: 'storelocator-fe8e7.firebaseapp.com',
    databaseURL: 'https://storelocator-fe8e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
    measurementId: 'G-MWR9070Q50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyniAB8Ewcd2mq4Ju55szARC2qV-0an64',
    appId: '1:106870549521:android:ba26f7a19a9bdb9f7c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    databaseURL: 'https://storelocator-fe8e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Ew7MWs9WXwN7lU6-teU3-UFx_4tghuM',
    appId: '1:106870549521:ios:9718e1233b85a2a87c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    databaseURL: 'https://storelocator-fe8e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
    iosBundleId: 'com.example.bilipatraRetailCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Ew7MWs9WXwN7lU6-teU3-UFx_4tghuM',
    appId: '1:106870549521:ios:9718e1233b85a2a87c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    databaseURL: 'https://storelocator-fe8e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
    iosBundleId: 'com.example.bilipatraRetailCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCShLKUvRcA0O6QTgH4ZL7QthTAIyFnohM',
    appId: '1:106870549521:web:a609ac8ceed426967c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    authDomain: 'storelocator-fe8e7.firebaseapp.com',
    databaseURL: 'https://storelocator-fe8e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
    measurementId: 'G-LWLR6B894S',
  );

}