// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCShLKUvRcA0O6QTgH4ZL7QthTAIyFnohM",
      authDomain: "storelocator-fe8e7.firebaseapp.com",
      databaseURL: "https://storelocator-fe8e7-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "storelocator-fe8e7",
      storageBucket: "storelocator-fe8e7.firebasestorage.app",
      messagingSenderId: "106870549521",
      appId: "1:106870549521:web:0f123668e7efb9f97c15b0",
      measurementId: "G-MWR9070Q50"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyniAB8Ewcd2mq4Ju55szARC2qV-0an64',
    appId: '1:106870549521:android:0b40f13fa47bc10c7c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Ew7MWs9WXwN7lU6-teU3-UFx_4tghuM',
    appId: '1:106870549521:ios:d206c04c8951f1617c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
    iosBundleId: 'com.example.b12greenfoodOrderonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Ew7MWs9WXwN7lU6-teU3-UFx_4tghuM',
    appId: '1:106870549521:ios:d206c04c8951f1617c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
    iosBundleId: 'com.example.b12greenfoodOrderonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCShLKUvRcA0O6QTgH4ZL7QthTAIyFnohM',
    appId: '1:106870549521:web:3ed174c07e1ee9ac7c15b0',
    messagingSenderId: '106870549521',
    projectId: 'storelocator-fe8e7',
    authDomain: 'storelocator-fe8e7.firebaseapp.com',
    storageBucket: 'storelocator-fe8e7.firebasestorage.app',
    measurementId: 'G-2EVRHFX24K',
  );

}