import 'package:bilipatra_retail_counter/services/api_service.dart';
import 'package:bilipatra_retail_counter/services/invoice_generator.dart';
import 'package:bilipatra_retail_counter/services/network_aware_wrapper.dart';
import 'package:bilipatra_retail_counter/services/notification_service.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';

import 'firebase_options.dart';
import 'providers/app_provider.dart';
import 'providers/auth_provider.dart';
import 'routes/app_router.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

import 'package:http/http.dart' as http;
import 'dart:convert';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 🔧 Setup flutter_local_notifications plugin before using it
  await NotificationService.instance.setupFlutterNotifications();

  // ✅ Now initialize FCM and related configurations
  await NotificationService.instance.initialize();

  // 🧪 Debug: Print FCM Token
  String? token = await FirebaseMessaging.instance.getToken();
  print('🔔 FCM Token: $token');

  // Foreground message listener
  FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
    print("🔔 Foreground notification: ${message.notification?.title}");

    // Show as local notification when app is in foreground
    await NotificationService.instance.showNotification(message);
  });

  runApp(const BilipatraApp());
}

class BilipatraApp extends StatefulWidget {
  const BilipatraApp({super.key});

  @override
  State<BilipatraApp> createState() => _BilipatraAppState();
}

class _BilipatraAppState extends State<BilipatraApp> {
  late final AuthProvider _authProvider;
  late final GoRouter _appRouter;

  @override
  void initState() {
    super.initState();
    _authProvider = AuthProvider();
    _appRouter = createAppRouter(_authProvider);
  }

  @override
  void dispose() {
    _authProvider.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AppProvider()),
        ChangeNotifierProvider.value(value: _authProvider),
      ],
      child: MaterialApp.router(
        debugShowCheckedModeBanner: false,
        title: 'Bilipatra Retail Counter',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.green.shade600),
          useMaterial3: true,
        ),

        // 🟢 THE NETWORK WRAPPER INJECTION 🟢
        // This wraps every single screen generated by go_router
        builder: (context, child) {
          return NetworkAwareWrapper(child: child ?? const SizedBox.shrink());
        },

        routerConfig: _appRouter,
      ),
    );
  }
}
